on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2

      - name: "Install R"
        uses: r-lib/actions/setup-r@v2

      - name: "Install Dependencies"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ./R

      - name: Generate data
        run: Rscript R/createMappingData.R

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/*
          git diff-index --quiet HEAD || (git commit -m "Vaccination data update: $(date)" && git push)
